#@ load("@ytt:overlay", "overlay")
#@data/values
---
#@overlay/match missing_ok=True
images:
  metric_proxy: "index.docker.io/cloudfoundry/metric-proxy@sha256:c38e25699459341aad51d7be5c08b0d9b127170ebac92e3d39c47d4ff666b6fd"