#@ load("@ytt:overlay", "overlay")
#@data/values
---
#@overlay/match missing_ok=True
images:
  metric_proxy: "index.docker.io/cloudfoundry/metric-proxy@sha256:8ca31d73a4dd557dbe6decc09966b3801fe33f28bcac423d83d5baa9d5e2a53f"