platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-dind

params:
  DOCKERHUB_USERNAME: ((dockerhub.username))
  DOCKERHUB_PASSWORD: ((dockerhub.password))
  GIT_COMMIT_EMAIL: cf-release-integration@pivotal.io
  GIT_COMMIT_USERNAME: "relint-ci"

inputs:
  - name: metric-proxy

outputs:
  - name: updated-metric-proxy

run:
  path: metric-proxy/ci/tasks/build-image/task.sh
