platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-dind

params:
  DOCKERHUB_USERNAME: ((dockerhub.username))
  DOCKERHUB_PASSWORD: ((dockerhub.password))

inputs:
  - name: metric-proxy
  - name: metric-proxy-ci

outputs:
  - name: updated-metric-proxy

run:
  path: metric-proxy-ci/ci/tasks/build-image/task.sh
