---
platform: linux

image_resource:
  type: docker-image
  source: {repository: relintdockerhubpushbot/cf-for-k8s-ci}

inputs:
- name: metric-proxy-docker
- name: cf-for-k8s
- name: metric-proxy

outputs:
- name: cf-for-k8s-with-metrics
  path: cf-for-k8s

run:
  path: metric-proxy/ci/tasks/vendir-metrics.sh
