#@ load("@ytt:data", "data")
#@ load("/namespaces.star", "system_namespace")
---
apiVersion: v1
kind: Service
metadata:
  name: metric-proxy
  namespace: #@ system_namespace()
spec:
  selector:
    app: metric-proxy
  ports:
    - protocol: TCP
      port: 8080
      name: https
