#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Service
metadata:
  name: metric-proxy
  namespace: #@ data.values.system_namespace
  labels: #@ data.values.metadata_labels()
spec:
  selector:
    app: metric-proxy
  ports:
    - protocol: TCP
      port: 8080
      name: https
