groups:
  - name: tests
    jobs:
      - metric-proxy-unit-tests
      - build-metric-proxy-image
      - test-metric-proxy-bump-on-cf-for-k8s
  - name: ship-it
    jobs:
      - metric-proxy-cut-major
      - metric-proxy-cut-minor
      - metric-proxy-cut-patch
      - create-metric-proxy-release

resources:
- name: metric-proxy-trigger
  type: git
  source:
    branch: main
    uri: git@github.com:cloudfoundry/metric-proxy
    private_key: ((oratos-bot-private-key))
    ignore_paths:
    - README.md
    - version
    - docs/**
    - ci/**
    - config/values/images.yml

- name: metric-proxy
  type: git
  source:
    branch: main
    uri: git@github.com:cloudfoundry/metric-proxy
    private_key: ((oratos-bot-private-key))

- name: metric-proxy-version
  type: semver
  source:
    branch: main
    driver: git
    file: version
    # on 2 lines because: https://github.com/concourse/semver-resource/issues/79
    private_key: |
      ((oratos-bot-private-key))
    uri: git@github.com:cloudfoundry/metric-proxy.git

- name: cf-for-k8s-main
  type: git
  source:
    branch: main
    uri: git@github.com:cloudfoundry/cf-for-k8s
    private_key: ((oratos-bot-private-key))

- name: cf-for-k8s-ci
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/cf-for-k8s
    branch: develop
    private_key: ((cf_for_k8s_readonly_deploy_key.private_key))
    paths:
    - ci/**

- name: ready-pool
  type: pool
  icon: pool
  source:
    uri: git@github.com:cloudfoundry/relint-ci-pools
    branch: main
    pool: k8s-dev/ready
    private_key: ((relint_ci_pools_readwrite_deploy_key.private_key))

- name: destroy-pool
  type: pool
  icon: pool
  source:
    uri: git@github.com:cloudfoundry/relint-ci-pools
    branch: main
    pool: k8s-dev/destroy
    private_key: ((relint_ci_pools_readwrite_deploy_key.private_key))

- name: metric-proxy-image
  type: registry-image
  source:
    repository: cloudfoundry/metric-proxy
    username: ((dockerhub.username))
    password: ((dockerhub.password))

- name: metric-proxy-github-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: metric-proxy
    access_token: ((logging-github-access-token))
    drafts: true

jobs:
  - name: metric-proxy-unit-tests
    public: true
    plan:
    - in_parallel:
      - get: metric-proxy-trigger
        trigger: true
      - get: metric-proxy
    - task: run-metric-proxy-unit-tests
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: cloudfoundry/cf-for-k8s-ci
        inputs:
        - name: metric-proxy
        run:
          path: bash
          args:
          - -euc
          - |
            cd metric-proxy
            go test -v ./pkg/...

  - name: build-metric-proxy-image
    plan:
      - in_parallel:
          - get: metric-proxy
            trigger: true
            passed: ["metric-proxy-unit-tests"]
          - get: metric-proxy-version
      - task: build-image-and-update-image-ref
        privileged: true
        file: metric-proxy/ci/tasks/build-image/task.yml
      - put: metric-proxy
        params:
          repository: updated-metric-proxy
          rebase: true

  - name: test-metric-proxy-bump-on-cf-for-k8s
    public: true
    plan:
    - in_parallel:
      - get: cf-for-k8s-main
      - get: cf-for-k8s-ci
      - get: metric-proxy
        trigger: true
        passed:
          - build-metric-proxy-image
      - get: metric-proxy-image

    - put: ready-pool
      params:
        acquire: true

    - task: bump-metric-proxy-in-cf-for-k8s
      input_mapping:
        cf-for-k8s: cf-for-k8s-main
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: cloudfoundry/cf-for-k8s-ci
        inputs:
          - name: cf-for-k8s
          - name: metric-proxy
        outputs:
          - name: updated-cf-for-k8s
        run:
          path: /bin/bash
          args:
            - -c
            - |
              set -euo pipefail
              pushd cf-for-k8s
                vendir sync -d config/metrics/_ytt_lib/metric-proxy="../metric-proxy/config"
              popd
              cp -r cf-for-k8s/* updated-cf-for-k8s/

    - task: install-cf
      file: cf-for-k8s-ci/ci/tasks/install-cf-on-gke/task.yml
      input_mapping:
        pool-lock: ready-pool
        cf-for-k8s: updated-cf-for-k8s
      params:
        GCP_SERVICE_ACCOUNT_JSON: ((ci_k8s_gcp_service_account_json))
        GCP_PROJECT_NAME: ((ci_k8s_gcp_project_name))
        GCP_PROJECT_ZONE: ((ci_k8s_gcp_project_zone))
        DOMAIN: k8s-dev.relint.rocks

    - task: run-smoke-tests
      file: cf-for-k8s-ci/ci/tasks/run-smoke-tests/task.yml
      input_mapping:
        cf-for-k8s: updated-cf-for-k8s
      params:
        SMOKE_TEST_SKIP_SSL: false

    - task: delete-cf
      file: cf-for-k8s-ci/ci/tasks/delete-cf/task.yml
      input_mapping:
        pool-lock: ready-pool
      params:
        GCP_PROJECT_NAME: ((ci_k8s_gcp_project_name))
        GCP_PROJECT_ZONE: ((ci_k8s_gcp_project_zone))
        GCP_SERVICE_ACCOUNT_JSON: ((ci_k8s_gcp_service_account_json))

    ensure:
      do:
      - put: destroy-pool
        params:
          add: ready-pool

      - put: ready-pool
        params:
          remove: ready-pool

  - name: metric-proxy-cut-patch
    public: true
    plan:
    - put: metric-proxy-version
      params: {bump: patch}

  - name: metric-proxy-cut-minor
    public: true
    plan:
    - put: metric-proxy-version
      params: {bump: minor}

  - name: metric-proxy-cut-major
    public: true
    plan:
    - put: metric-proxy-version
      params: {bump: major}

  - name: create-metric-proxy-release
    public: true
    plan:
    - in_parallel:
      - get: metric-proxy
        passed: ["test-metric-proxy-bump-on-cf-for-k8s"]
    - task: prepare-release
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: cloudfoundry/cf-for-k8s-dind}
        inputs:
          - name: metric-proxy
        outputs:
          - name: metric-proxy-release
        run:
          path: /bin/bash
          args:
          - -ce
          - |
            version=$(cat metric-proxy/version)

            echo $version > metric-proxy-release/name

            pushd metric-proxy
              git rev-parse HEAD > ../metric-proxy-release/commitish

              sed -i "s|version:.*|version: $version|" config/values/_defaults.yml
            popd

            mkdir metric-proxy-release/globs
            cp metric-proxy/config/*.yml metric-proxy/config/values/*.yml metric-proxy-release/globs/

            cat << EOF > metric-proxy-release/body
            ### Changelog

            **Version**
            $version

            EOF
    - put: metric-proxy-github-release
      params:
        name: metric-proxy-release/name
        tag: metric-proxy-release/name
        globs:
        - metric-proxy-release/globs/*
        commitish: metric-proxy-release/commitish
        body: metric-proxy-release/body
